#!/bin/bash
for folder in src/*; do
	package=$(sed -n 's/^Package: \+//p' $folder/DEBIAN/control)
	version=$(sed -n 's/^Version: \+//p' $folder/DEBIAN/control)
	architecture=$(sed -n 's/^Architecture: \+//p' $folder/DEBIAN/control)
	dpkg-deb --build $folder "$package-$version-$architecture.deb"
done
